Fix issue with missing masking of AT%CHLD
drivers/calypsomodem/voicecall.c: In function ‘calypso_release_specific’:
drivers/calypsomodem/voicecall.c:162: error: too few arguments for format